CREATE TABLE IF NOT EXISTS tb_entity (
  id VARCHAR(8) PRIMARY KEY,
  tenant_id VARCHAR(8) NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  data TEXT,
  description VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);